command:
  - uvicorn
  - "--app-dir"
  - "apps/backend"
  - "main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: DATABRICKS_SERVER_HOSTNAME
    value: ${DATABRICKS_SERVER_HOSTNAME}
  - name: DATABRICKS_TOKEN
    value: ${DATABRICKS_TOKEN}
  - name: DATABRICKS_WAREHOUSE_HTTP_PATH
    value: "/sql/1.0/warehouses/b4526cd9412a6183"