import type { Metadata } from "next";
import "../styles/globals.css";
import Sidebar from "../components/Sidebar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex">
        <Sidebar />
        <main className="flex-1 md:ml-60">{children}</main>
        <Toaster richColors />
      </body>
    </html>
  );
}
