import type { Metadata } from "next";
import "../styles/globals.css";
import Sidebar from "../components/Sidebar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex">
        <Sidebar />
        <main className="flex-1" style={{ marginLeft: 'var(--sidebar-width)' }}>
          {children}
        </main>
        <Toaster theme="dark" richColors />
      </body>
    </html>
  );
}
